# Generated by Django 5.2.7 on 2025-10-30 21:50

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('permissionid', models.AutoField(db_column='PermissionID', primary_key=True, serialize=False)),
                ('permission', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Permission', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'db_table': 'tbl_Permission',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleid', models.AutoField(db_column='RoleID', primary_key=True, serialize=False)),
                ('role', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Role', max_length=50, unique=True)),
                ('description', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'db_table': 'tbl_Role',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.IntegerField(db_column='UserID', primary_key=True, serialize=False)),
                ('user', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='User', max_length=50, unique=True)),
                ('passphrase', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PassPhrase', max_length=100)),
                ('active', models.BooleanField(db_column='Active')),
                ('priority', models.SmallIntegerField(db_column='Priority')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'tbl_User',
            },
        ),
        migrations.CreateModel(
            name='Userlogin',
            fields=[
                ('loginid', models.AutoField(db_column='LoginID', primary_key=True, serialize=False)),
                ('userid', models.IntegerField(db_column='UserID')),
                ('enterdate', models.DateTimeField(db_column='EnterDate')),
                ('exitdate', models.DateTimeField(blank=True, db_column='ExitDate', null=True)),
            ],
            options={
                'db_table': 'tbl_UserLogin',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('userroleid', models.AutoField(db_column='UserRoleID', primary_key=True, serialize=False)),
                ('all_projects', models.BooleanField(db_column='AllProjects', default=False, null=True)),
            ],
            options={
                'verbose_name': 'User_Project_Role',
                'verbose_name_plural': 'User_Projects_Roles',
                'db_table': 'tbl_JUserRole',
            },
        ),
        migrations.CreateModel(
            name='PmrsUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('personnel_code', models.PositiveIntegerField(null=True)),
                ('email', models.EmailField(max_length=150, null=True)),
                ('user_img', models.ImageField(blank=True, default='user_images/asft.png', null=True, upload_to='user_images')),
                ('priority', models.SmallIntegerField(db_column='Priority', default=0)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('rolepermissionid', models.AutoField(db_column='RolePermissionID', primary_key=True, serialize=False)),
                ('permissionid', models.ForeignKey(db_column='PermissionID', on_delete=django.db.models.deletion.PROTECT, related_name='Permission_RolePermission', to='accounts.permission')),
                ('roleid', models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.PROTECT, related_name='Role_RolePermission', to='accounts.role')),
            ],
            options={
                'verbose_name': 'Role_Permission',
                'verbose_name_plural': 'Role_Permissions',
                'db_table': 'tbl_JRolePermission',
            },
        ),
        migrations.AddField(
            model_name='permission',
            name='role',
            field=models.ManyToManyField(through='accounts.RolePermission', to='accounts.role'),
        ),
    ]
