# Generated by Django 5.2.7 on 2025-10-30 21:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='projectid',
            field=models.ForeignKey(blank=True, db_column='ContractID', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Contract_UserRole', to='contracts.contract'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='roleid',
            field=models.ForeignKey(db_column='RoleID', on_delete=django.db.models.deletion.PROTECT, related_name='Role_UserRole', to='accounts.role'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='userid',
            field=models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.PROTECT, related_name='User_UserRole', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='role',
            name='user',
            field=models.ManyToManyField(through='accounts.UserRole', to=settings.AUTH_USER_MODEL),
        ),
    ]
