# Generated by Django 5.2.7 on 2025-10-30 21:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyType',
            fields=[
                ('companytypeid', models.AutoField(db_column='CompanyTypeID', primary_key=True, serialize=False)),
                ('companytype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CompanyType', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'CompanyType',
                'verbose_name_plural': 'CompanyTypes',
                'db_table': 'tbl_CompanyType',
            },
        ),
        migrations.CreateModel(
            name='ContractContractor',
            fields=[
                ('contractcontractorid', models.AutoField(db_column='ContractContractorID', primary_key=True, serialize=False)),
                ('contractid', models.IntegerField(db_column='ContractID')),
                ('contractorid', models.IntegerField(db_column='ContractorID')),
            ],
            options={
                'db_table': 'tbl_JContractContractor',
            },
        ),
        migrations.CreateModel(
            name='ContractType',
            fields=[
                ('contracttypeid', models.AutoField(db_column='ContractTypeID', primary_key=True, serialize=False)),
                ('contracttype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ContractType', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'ContractType',
                'verbose_name_plural': 'ContractTypes',
                'db_table': 'tbl_ContractType',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('countryid', models.AutoField(db_column='CountryID', primary_key=True, serialize=False)),
                ('country', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Country', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'db_table': 'tbl_Country',
            },
        ),
        migrations.CreateModel(
            name='DateConversion',
            fields=[
                ('shamsidate', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ShamsiDate', max_length=10, primary_key=True, serialize=False)),
                ('georgiandate', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='GeorgianDate', max_length=10)),
                ('tmonth', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='tMonth', max_length=2)),
                ('monthtext', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='MonthText', max_length=50)),
                ('month', models.SmallIntegerField(db_column='Month')),
                ('year', models.IntegerField(db_column='Year')),
            ],
            options={
                'db_table': 'tbl_DateConvertion',
            },
        ),
        migrations.CreateModel(
            name='FinancialDocuments',
            fields=[
                ('documentid', models.IntegerField(db_column='DocumentID', primary_key=True, serialize=False)),
                ('documentno', models.IntegerField(db_column='DocumentNo')),
                ('doctype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='DocType', max_length=50)),
                ('description', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Description', max_length=255)),
                ('date', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Date', max_length=10)),
                ('contractno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ContractNo', max_length=20)),
                ('contract', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contract', max_length=255)),
                ('definitiveid', models.IntegerField(db_column='DefinitiveID')),
                ('definitive', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Definitive', max_length=255)),
                ('acp', models.BigIntegerField(db_column='ACP')),
                ('acz', models.BigIntegerField(db_column='ACZ')),
                ('retrievedate', models.DateField(db_column='RetrieveDate')),
                ('iscompleted', models.BooleanField(db_column='IsCompleted')),
                ('tmp', models.BooleanField()),
                ('costcenterid', models.IntegerField(blank=True, db_column='CostCenterID', null=True)),
                ('costcenter', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='CostCenter', max_length=255, null=True)),
            ],
            options={
                'db_table': 'tbl_FinancialDocuments',
            },
        ),
        migrations.CreateModel(
            name='Personeltype',
            fields=[
                ('personeltypeid', models.AutoField(db_column='PersonelTypeID', primary_key=True, serialize=False)),
                ('personeltype', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='PersonelType', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'PersonalType',
                'verbose_name_plural': 'PersonalTypes',
                'db_table': 'tbl_PersonelType',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('companyid', models.AutoField(db_column='CompanyID', primary_key=True, serialize=False)),
                ('company', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Company', max_length=200)),
                ('tel', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Tel', max_length=20, null=True)),
                ('fax', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Fax', max_length=20, null=True)),
                ('email', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Email', max_length=50, null=True)),
                ('address', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Address', max_length=200, null=True)),
                ('companytypeid', models.ForeignKey(db_column='CompanyTypeID', on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.companytype')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'tbl_Company',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contractid', models.AutoField(db_column='ContractID', primary_key=True, serialize=False, verbose_name='ContractID')),
                ('contractno', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ContractNo', max_length=50, verbose_name='Contract No')),
                ('contract', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contract', max_length=250, verbose_name='Contract')),
                ('startoperationdate', models.DateField(blank=True, db_column='StartOperationDate', null=True, verbose_name='Actual Start Date')),
                ('finishdate', models.DateField(blank=True, db_column='FinishDate', null=True, verbose_name='Finish Date')),
                ('notificationdate', models.DateField(blank=True, db_column='NotificationDate', null=True, verbose_name='Notification Date')),
                ('validationdate', models.DateField(blank=True, db_column='ValidationDate', null=True, verbose_name='Confirmation Date')),
                ('planstartdate', models.DateField(blank=True, db_column='PlanStartDate', null=True, verbose_name='Plan Start Date')),
                ('startdate', models.DateField(blank=True, db_column='StartDate', null=True, verbose_name='Start Date')),
                ('duration', models.IntegerField(blank=True, db_column='Duration', null=True, verbose_name='Duration')),
                ('prepaymentpercent', models.FloatField(blank=True, db_column='PrePaymentPercent', null=True, verbose_name='Prepayment Percent')),
                ('insurancepercent', models.FloatField(blank=True, db_column='InsurancePercent', null=True, verbose_name='Insurance Percent')),
                ('perforcebondpercent', models.FloatField(blank=True, db_column='PerforceBondPercent', null=True, verbose_name='Performance Bond Percent')),
                ('withholdingtaxpercent', models.FloatField(blank=True, db_column='WithholdingTaxPercent', null=True, verbose_name='Tax Percent')),
                ('commitpercent', models.FloatField(blank=True, db_column='CommitPercent', null=True, verbose_name='Commit Percent')),
                ('contractamount_r', models.BigIntegerField(blank=True, db_column='ContractAmount_R', null=True, verbose_name='Contract Amount R')),
                ('contractamount_fc', models.BigIntegerField(blank=True, db_column='ContractAmount_FC', null=True, verbose_name='Contract Amount FC')),
                ('schedulelevel', models.SmallIntegerField(db_column='ScheduleLevel')),
                ('version', models.IntegerField(db_column='Version')),
                ('currencybprice', models.IntegerField(blank=True, db_column='CurrencyBPrice', null=True)),
                ('currencyuprice', models.IntegerField(blank=True, db_column='CurrencyUPrice', null=True)),
                ('attachmentcontractprice1_r', models.BigIntegerField(blank=True, db_column='AttachmentContractPrice1_R', null=True)),
                ('attachmentcontractprice1_fc', models.BigIntegerField(blank=True, db_column='AttachmentContractPrice1_FC', null=True)),
                ('attachmentcontractprice2_r', models.BigIntegerField(blank=True, db_column='AttachmentContractPrice2_R', null=True)),
                ('attachmentcontractprice2_fc', models.BigIntegerField(blank=True, db_column='AttachmentContractPrice2_FC', null=True)),
                ('attachmentcontractprice3_r', models.BigIntegerField(blank=True, db_column='AttachmentContractPrice3_R', null=True)),
                ('attachmentcontractprice3_fc', models.BigIntegerField(blank=True, db_column='AttachmentContractPrice3_FC', null=True)),
                ('attachmentcontractprice4_r', models.BigIntegerField(blank=True, db_column='AttachmentContractPrice4_R', null=True)),
                ('attachmentcontractprice4_fc', models.BigIntegerField(blank=True, db_column='AttachmentContractPrice4_FC', null=True)),
                ('attachmentcontractprice5_r', models.BigIntegerField(blank=True, db_column='AttachmentContractPrice5_R', null=True)),
                ('attachmentcontractprice5_fc', models.BigIntegerField(blank=True, db_column='AttachmentContractPrice5_FC', null=True)),
                ('location', models.CharField(db_column='Location', max_length=20, null=True, verbose_name='Location')),
                ('latitude', models.FloatField(db_column='Latitude', null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(db_column='Longitude', null=True, verbose_name='Longitude')),
                ('iscompleted', models.BooleanField(blank=True, db_column='IsCompleted', null=True, verbose_name='Is Completed')),
                ('completeddate', models.IntegerField(blank=True, db_column='CompletedDate', null=True, verbose_name='Completed Date')),
                ('coordinatorid', models.ForeignKey(blank=True, db_column='CoordinatorID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Coordinator_Contract', to=settings.AUTH_USER_MODEL, verbose_name='Coordinator')),
                ('customerid', models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, related_name='Customer_Contract', to='contracts.company', verbose_name='Customer')),
                ('projectmanagerid', models.ForeignKey(db_column='ProjectManagerID', on_delete=django.db.models.deletion.CASCADE, related_name='ProjectManager_Contract', to=settings.AUTH_USER_MODEL)),
                ('contracttypeid', models.ForeignKey(db_column='ContractTypeID', on_delete=django.db.models.deletion.CASCADE, related_name='ContractType_Contract', to='contracts.contracttype', verbose_name='Contract Type')),
            ],
            options={
                'verbose_name': 'Contract',
                'verbose_name_plural': 'Contracts',
                'db_table': 'tbl_Contract',
            },
        ),
        migrations.CreateModel(
            name='Addendum',
            fields=[
                ('addendumid', models.AutoField(db_column='AddendumID', primary_key=True, serialize=False)),
                ('addendumamount_r', models.BigIntegerField(db_column='AddendumAmount_R', null=True)),
                ('addendumamount_fc', models.IntegerField(db_column='AddendumAmount_FC', null=True)),
                ('addendumamountdate', models.DateField(db_column='AddendumAmountDate', default=django.utils.timezone.now, null=True)),
                ('afteraddendumdate', models.DateField(db_column='AfterAddendumDate', null=True)),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.PROTECT, related_name='Contract_Addendum', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract_Addendum',
                'verbose_name_plural': 'Contract_Addendums',
                'db_table': 'tbl_Addendum',
            },
        ),
        migrations.CreateModel(
            name='ContractConsultant',
            fields=[
                ('contractconsultantid', models.AutoField(db_column='ContractConsultantID', primary_key=True, serialize=False)),
                ('consultantid', models.ForeignKey(db_column='ConsultantID', on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.company')),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract_Consultant',
                'verbose_name_plural': 'Contract_Consultants',
                'db_table': 'tbl_JContractConsultant',
            },
        ),
        migrations.CreateModel(
            name='ContractCurrencies',
            fields=[
                ('contractcurrencyid', models.AutoField(db_column='ContractCurrencyID', primary_key=True, serialize=False)),
                ('currencyid', models.IntegerField(db_column='CurrencyID')),
                ('price', models.IntegerField(db_column='Price')),
                ('date', models.DateField(db_column='Date')),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract_Currency',
                'verbose_name_plural': 'Contract_Currencies',
                'db_table': 'tbl_JContractCurrencies',
            },
        ),
        migrations.CreateModel(
            name='ContractUser',
            fields=[
                ('contractuserid', models.AutoField(db_column='ContractUserID', primary_key=True, serialize=False)),
                ('type', models.BooleanField(blank=True, db_column='Type', null=True)),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.contract')),
                ('userid', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contract_User',
                'verbose_name_plural': 'Contract_Users',
                'db_table': 'tbl_JContractUser',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('currencyid', models.AutoField(db_column='CurrencyID', primary_key=True, serialize=False)),
                ('currency', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Currency', max_length=50)),
                ('countryid', models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.country')),
            ],
            options={
                'verbose_name': 'Currency',
                'verbose_name_plural': 'Currencies',
                'db_table': 'tbl_Currency',
            },
        ),
        migrations.AddField(
            model_name='contract',
            name='currencyid',
            field=models.ForeignKey(blank=True, db_column='CurrencyID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Currency_Contract', to='contracts.currency', verbose_name='Currency'),
        ),
        migrations.CreateModel(
            name='EpcCorporation',
            fields=[
                ('contractcorporationid', models.AutoField(db_column='ContractCorporationID', primary_key=True, serialize=False)),
                ('e_percent', models.FloatField(db_column='E_Percent')),
                ('p_percent', models.FloatField(db_column='P_Percent')),
                ('c_percent', models.FloatField(db_column='C_Percent')),
                ('companyid', models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='Company_Corporation', to='contracts.company')),
                ('contractid', models.ForeignKey(db_column='ContractID', on_delete=django.db.models.deletion.CASCADE, related_name='Contract_Corporation', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Contract_Corporation',
                'verbose_name_plural': 'Contract_Corporations',
                'db_table': 'tbl_Corporation',
            },
        ),
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('personelid', models.IntegerField(db_column='PersonelID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Name', max_length=50)),
                ('family', models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Family', max_length=50)),
                ('tel', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Tel', max_length=20, null=True)),
                ('activity', models.CharField(blank=True, db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Activity', max_length=50, null=True)),
                ('active', models.BooleanField(db_column='Active')),
                ('personeltypeid', models.ForeignKey(db_column='PersonelTypeID', on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.personeltype')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personals',
                'db_table': 'tbl_Personel',
            },
        ),
    ]
