# Generated by Django 3.2.19 on 2024-12-30 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_auto_20240709_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='contractid',
            field=models.AutoField(db_column='ContractID', primary_key=True, serialize=False, verbose_name='ContractID'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractno',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='ContractNo', max_length=50, verbose_name='Contract No'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contracttypeid',
            field=models.ForeignKey(db_column='ContractTypeID', on_delete=django.db.models.deletion.CASCADE, related_name='ContractType_Contract', to='contracts.contracttype', verbose_name='ContractTypeID'),
        ),
    ]
