# Generated by Django 3.2.19 on 2024-12-30 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contracts', '0004_auto_20241230_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='commitpercent',
            field=models.FloatField(blank=True, db_column='CommitPercent', null=True, verbose_name='Commit Percent'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='completeddate',
            field=models.IntegerField(blank=True, db_column='CompletedDate', null=True, verbose_name='Completed Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contract',
            field=models.CharField(db_collation='SQL_Latin1_General_CP1_CI_AS', db_column='Contract', max_length=250, verbose_name='Contract'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractamount_fc',
            field=models.BigIntegerField(blank=True, db_column='ContractAmount_FC', null=True, verbose_name='Contract Amount FC'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contractamount_r',
            field=models.BigIntegerField(blank=True, db_column='ContractAmount_R', null=True, verbose_name='Contract Amount R'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='contracttypeid',
            field=models.ForeignKey(db_column='ContractTypeID', on_delete=django.db.models.deletion.CASCADE, related_name='ContractType_Contract', to='contracts.contracttype', verbose_name='Contract Type'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='coordinatorid',
            field=models.ForeignKey(blank=True, db_column='CoordinatorID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Coordinator_Contract', to=settings.AUTH_USER_MODEL, verbose_name='Coordinator'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='currencyid',
            field=models.ForeignKey(blank=True, db_column='CurrencyID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Currency_Contract', to='contracts.currency', verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='customerid',
            field=models.ForeignKey(db_column='CustomerID', on_delete=django.db.models.deletion.CASCADE, related_name='Customer_Contract', to='contracts.company', verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='duration',
            field=models.IntegerField(blank=True, db_column='Duration', null=True, verbose_name='Duration'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='finishdate',
            field=models.DateField(blank=True, db_column='FinishDate', null=True, verbose_name='Finish Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='insurancepercent',
            field=models.FloatField(blank=True, db_column='InsurancePercent', null=True, verbose_name='Insurance Percent'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='iscompleted',
            field=models.BooleanField(blank=True, db_column='IsCompleted', null=True, verbose_name='Is Completed'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='latitude',
            field=models.FloatField(db_column='Latitude', null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='location',
            field=models.CharField(db_column='Location', max_length=20, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='longitude',
            field=models.FloatField(db_column='Longitude', null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='notificationdate',
            field=models.DateField(blank=True, db_column='NotificationDate', null=True, verbose_name='Notification Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='perforcebondpercent',
            field=models.FloatField(blank=True, db_column='PerforceBondPercent', null=True, verbose_name='Performance Bond Percent'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='planstartdate',
            field=models.DateField(blank=True, db_column='PlanStartDate', null=True, verbose_name='Plan Start Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='prepaymentpercent',
            field=models.FloatField(blank=True, db_column='PrePaymentPercent', null=True, verbose_name='Prepayment Percent'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='startdate',
            field=models.DateField(blank=True, db_column='StartDate', null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='startoperationdate',
            field=models.DateField(blank=True, db_column='StartOperationDate', null=True, verbose_name='Actual Start Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='validationdate',
            field=models.DateField(blank=True, db_column='ValidationDate', null=True, verbose_name='Confirmation Date'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='withholdingtaxpercent',
            field=models.FloatField(blank=True, db_column='WithholdingTaxPercent', null=True, verbose_name='Tax Percent'),
        ),
    ]
