# Generated by Django 3.2.19 on 2025-01-11 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0005_auto_20241230_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='country',
        ),
        migrations.AddField(
            model_name='currency',
            name='countryid',
            field=models.IntegerField(db_column='CountryID', default=0),
            preserve_default=False,
        ),
    ]
