# Generated by Django 3.2.19 on 2025-01-11 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0006_auto_20250111_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='countryid',
            field=models.ForeignKey(db_column='CountryID', on_delete=django.db.models.deletion.DO_NOTHING, to='contracts.country'),
        ),
    ]
