# Generated by Django 3.2.19 on 2024-08-26 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_invoice_senddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialinvoice',
            name='senddate',
            field=models.DateTimeField(blank=True, db_column='SendDate', default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='senddate',
            field=models.DateTimeField(blank=True, db_column='SendDate', default=django.utils.timezone.now, null=True),
        ),
    ]
