# Generated by Django 3.2.19 on 2025-01-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20240826_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectpersonnel',
            name='cocpno',
            field=models.IntegerField(db_column='CentralOfficeConstructionPersonalNo', default=0),
        ),
        migrations.AddField(
            model_name='projectpersonnel',
            name='coepno',
            field=models.IntegerField(db_column='CentralOfficeEngineeringPersonalNo', default=0),
        ),
        migrations.AddField(
            model_name='projectpersonnel',
            name='copmpno',
            field=models.IntegerField(db_column='CentralOfficeProjectManagerPersonalNo', default=0),
        ),
        migrations.AddField(
            model_name='projectpersonnel',
            name='coppno',
            field=models.IntegerField(db_column='CentralOfficeProcurementPersonalNo', default=0),
        ),
        migrations.AddField(
            model_name='projectpersonnel',
            name='wsaopno',
            field=models.IntegerField(db_column='WorkshopAdministrativeOfficePersonalNo', default=0),
        ),
        migrations.AddField(
            model_name='projectpersonnel',
            name='wscaopno',
            field=models.IntegerField(db_column='WorkshopContractorAdministrativeOfficePersonalNo', default=0),
        ),
        migrations.AddField(
            model_name='projectpersonnel',
            name='wscpno',
            field=models.IntegerField(db_column='WorkshopConstructionPersonalNo', default=0),
        ),
    ]
