# Generated by Django 3.2.19 on 2025-03-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20250117_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinary',
            name='priority',
            field=models.BooleanField(db_column='Priority', default=False, null=True),
        ),
    ]
